# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: config set ignore-engines true
    - uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
    - uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: deploy
